Data:
  groundtruth_path: './HCP3D/train_patch/*/T1w/hr.npy' #'./HCP3D/train/*/T1w/*_groundtruth_norm.nii.gz'
  lowres_path: './HCP3D/train_patch/*/T1w/lr.npy' #'./HCP3D/train/*/T1w/lr_norm*.gz'
  groundtruth_path_test: './HCP3D/valid/*/T1w/*_groundtruth_norm.nii.gz'
  lowres_path_test: './HCP3D/valid/*/T1w/lr_norm*.gz'

Train:
  batch_size: 2
  save_file: './results/train_loss.csv'
  save_model: './results/model/checkpoint.pt'
  save_last_model: './results/model/last_checkpoint.pt'

Eval:
  batch_size: 2
  save_file: './results/valid_loss.csv'
  save_imgs: './results/figures/'